### ISSUE TITLE
Config Error: What am I missing?  Container Images not caching.

### ISSUE THREAD

**Issue by albal** [Trow-Registry/trow#393]
So I've installed Trow through helm on my cluster using `version: 0.8.1`.  It installs fine and I am able to view logs but when I create new pods with images I've not used before it doesn't seem that Trow is storing them.  I'm checking that by running `curl` on the `_catalog` endpoint:
```bash
$ curl -ks https://registry.ubiquitycluster.uk/v2/_catalog
{"repositories":[]}
```

When Trow starts this is the log:
```bash
$ kubectl logs -f trow-0 -n trow
Starting Trow 0.6.4 on 0.0.0.0:8000
Hostname of this registry (for the MutatingWebhook): "registry.[redacted].uk"
Image validation webhook configured:
  Default action: Deny
  Allowed prefixes: ["127.0.0.1"]
  Denied prefixes: []
Proxy registries configured:
  - docker: registry-1.docker.io
  - ghcr: ghcr.io
2025-01-12T19:58:16.996054Z DEBUG trow: Starting Trow server
2025-01-12T19:58:19.841623Z DEBUG request{method="GET" path="/v2/_catalog"}: tower_http::trace::on_request: started processing request
2025-01-12T19:58:19.842179Z  INFO request{method="GET" path="/v2/_catalog"}: trow::client_interface: Getting image catalog limit 4294967295 last_repo
2025-01-12T19:58:19.842578Z  INFO request{method="GET" path="/v2/_catalog"}: trow::routes: done in 1.160508ms
2025-01-12T19:58:21.876648Z DEBUG request{method="GET" path="/v2/_catalog"}: tower_http::trace::on_request: started processing request
```

This is my values.yaml:
```yaml
trow:
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  trow:
    domain: registry.[redacted].uk
    proxyRegistries:
      ## The Trow mutating webhook will automatically rewrite the pod image URLs to use the Trow proxy.
      webhook:
        enabled: true
        failurePolicy: Ignore
      config:
        offline: true
        registries:
          - alias: docker
            host: registry-1.docker.io
          - alias: ghcr
            host: ghcr.io
            ignore_repos: ["trow-registry/trow"]
  ## For more info on log levels see https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/filter/struct.EnvFilter.html
    logLevel: debug
    validatingWebhook:
      config:
        allow:
        - 127.0.0.1
        default: Allow
        deny: []
      enabled: false
      failurePolicy: ignore

  ingress:
    enabled: true
    annotations:
      # See ../docs/reference/ingress.md for more information
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-name: route
      nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
      nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
      #cert-manager.io/cluster-issuer:
      # enables cert-manager to issue a certificate for this ingress.
      # if you want to use a self-signed certificate, comment out the line below
      # and uncomment the line below that.
      cert-manager.io/cluster-issuer: pebble-issuer
      #cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      hajimari.io/enable: 'false'
    hosts:
    - host: registry.[redacted].uk
      paths:
      - /
    tls:
    - secretName: trow-tls-certificate
      hosts:
      - registry.[redacted].uk
  volumeClaim:
    storageClassName: longhorn
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
```

I've tried pulling images on Docker Hub and also GHCR with the same results - the pod starts but the pod image points to the original source and the image is not cached in Trow.

**Comment by albal** [comment]
So I am seeing the `trow-admission` service is not being created but the pods are there. 

Can anyone confirm which version of the helm chart is working?

**Comment by awoimbee** [comment]
Ah I see the issue with the service: `{{ if .Values.trow.validationWebhook.enabled }}` that should be an `or` (`{{ if or .Values.trow.validationWebhook.enabled .Values.trow.proxyRegistries.webhook.enabled }}`) or better yet, a variable in `_helpers.tpl`

**Comment by albal** [comment]
Trow is now rewriting the image but it is inserting an `f` and `_catalog` is still empty:
```yaml
image: registry.[redacted].uk/f/docker/library/alpine:3.3
```

**Comment by albal** [comment]
Ah I think I see the issue:

```bash
INFO request{method="POST" path="/mutate-image"}: trow::trow_server::admission: mutate_admission: proxying image alpine:3.4 to docker
```

K3S does not use Docker.

**Comment by awoimbee** [comment]
> K3S does not use Docker.

What this log means is that you setup Trow to proxy images from "registry-1.docker.io" under the alias "docker":
```
          - alias: docker
            host: registry-1.docker.io
```
(`alpine:3.4` is resolved as `registry-1.docker.io/_library/alpine:3.4`)

**Comment by albal** [comment]
@awoimbee I have gone back and forth between Trow helm charts and `values.yaml` files and still have the issue where trow is saying it is proxying the image but it doesn't seem to get written:

`Chart.yaml`:
```yaml
apiVersion: v2
name: trow
version: 0.0.0
dependencies:
  - name: trow
    version: 0.8.1
    repository: https://trow.io
```

`values.yaml`:
```yaml
trow:
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  trow:
    domain: registry.[redacted].uk
    # user: user
    # password: password
    validationWebhook:
      enabled: false
    proxyRegistries:
      webhook:
        enabled: true
      config:
        offline: false
        registries:
          - alias: docker
            host: registry-1.docker.io
          - alias: quay
            host: quay.io
          - alias: nvcr
            host: nvcr.io
          - alias: ghcr
            host: ghcr.io
            ignore_repos: ["trow-registry/trow"]
          - alias: k8s
            host: registry.k8s.io
          - alias: cern
            host: registry.cern.ch
    logLevel: debug
  ingress:
    enabled: true
    annotations:
      # See ../docs/reference/ingress.md for more information
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-name: route
      nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
      nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
      #cert-manager.io/cluster-issuer:
      # enables cert-manager to issue a certificate for this ingress.
      # if you want to use a self-signed certificate, comment out the line below
      # and uncomment the line below that.
      cert-manager.io/cluster-issuer: pebble-issuer
      #cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      hajimari.io/enable: 'false'
    hosts:
    - host: registry.[redacted].uk
      paths:
      - /
    tls:
    - secretName: trow-tls-certificate
      hosts:
      - registry.[redacted].uk
  volumeClaim:
    storageClassName: longhorn
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
```

`kubectl logs -f -n trow trow-webhook-b588796f6-gv5x2`:
```text
2025-01-14T13:06:18.792120Z DEBUG request{method="POST" path="/mutate-image"}: tower_http::trace::on_request: started processing request
2025-01-14T13:06:18.792925Z  INFO request{method="POST" path="/mutate-image"}: trow::client_interface: Mutating admission request 240cc37c-1aae-49e6-8024-a06667ec08fc host_name "registry.ubiquitycluster.uk"
2025-01-14T13:06:18.793058Z  INFO request{method="POST" path="/mutate-image"}: trow::trow_server::admission: mutate_admission: proxying image longhornio/longhorn-instance-manager:v1.7.2 to docker
2025-01-14T13:06:18.793197Z  INFO request{method="POST" path="/mutate-image"}: trow::routes: done in 1.113361ms
```  

Debug doesn't really offer any more detailed information. 

Catalog is empty:

```bash
$ curl -ks https://registry.[redacted].uk/v2/_catalog
{"repositories":[]}
```

**Comment by albal** [comment]
Okay so this is the thing I was missing:

You need a trusted cert - I was using pebble issuer for cluster certs but Trow expect a valid trusted cert.

Once I sorted that out images started to be sent to `Trow-0` pod and then show up in the regisitry.

Sorry to have been a bother.  Cheers.
